name: Pull Request Preview

on: [pull_request]

jobs:
  publish_preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: app/yarn.lock

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 6.x
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Publish preview
        run: eas update --branch preview

      - name: Comment preview
        uses: expo/expo-github-action/preview-comment@v8
        with:
          project: ./app
          command: eas update --auto
