name: Generate production preview

on:
  pull_request: 
    branches: 
      - main  

jobs:
  update-production:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install npm dependencies
        run: npm install

      - name: Run lint
        run: npm run format

      # - name: Run tests
      #   run: npm test

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Config environment variables
        run: |
          echo "${{ secrets.EAS_ENV_FILE }}" > .env
          echo "environment=prod" >> .env
          cat .env
  
          
      - name: Extract app version
        id: extract_version
        run: |
          VERSION=$(node -e "console.log(require('./app.config.js').expo.version)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "App Version => $VERSION"

      - name: Create preview
        run: |
          HEAD_REF="${{ github.event.pull_request.head.ref }}"
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          MESSAGE="${BASE_REF} <- ${HEAD_REF}"
          eas update --auto --branch "v$VERSION" --message "$MESSAGE"
      
      # - name: Build on EAS
      #   run: eas build --platform android --profile production --non-interactive --no-wait
